# Generated by Django 3.2 on 2023-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('nombre_huesped', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre_usuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=255)),
                ('sexo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], null=True)),
                ('rol', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administradores'), (2, 'Usuario avanzado'), (3, 'Usuario'), (4, 'Invitado')], null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
