# Generated by Django 3.2 on 2023-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacionesapp32', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrators'), (2, 'Avanced users'), (3, 'Common user'), (4, 'Guest')], null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman')], null=True),
        ),
    ]
